import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'hr' | 'en' | 'de' | 'it';

type Translations = Record<string, Record<Language, string>>;

const translations: Translations = {
  'app.title': { hr: 'ZadarIQ', en: 'ZadarIQ', de: 'ZadarIQ', it: 'ZadarIQ' },
  'app.subtitle': { hr: 'Pametni gradski asistent', en: 'Smart City Assistant', de: 'Smarter Stadtassistent', it: 'Assistente Città Intelligente' },
  'search.placeholder': { hr: 'Brzo pronađi…', en: 'Quick find…', de: 'Schnell finden…', it: 'Trova veloce…' },
  'search.results': { hr: 'Rezultati pretrage', en: 'Search Results', de: 'Suchergebnisse', it: 'Risultati della ricerca' },
  'status.open': { hr: 'OTVORENO', en: 'OPEN', de: 'GEÖFFNET', it: 'APERTO' },
  'status.closed': { hr: 'ZATVORENO', en: 'CLOSED', de: 'GESCHLOSSEN', it: 'CHIUSO' },
  'status.verified': { hr: 'Verificirano', en: 'Verified', de: 'Verifiziert', it: 'Verificato' },
  'status.community': { hr: 'Zajednica', en: 'Community', de: 'Gemeinschaft', it: 'Comunità' },
  'status.possiblyIncorrect': { hr: 'Moguće netočno', en: 'Possibly incorrect', de: 'Möglicherweise falsch', it: 'Possibilmente errato' },
  'action.call': { hr: 'Pozovi', en: 'Call', de: 'Anrufen', it: 'Chiama' },
  'action.navigate': { hr: 'Navigiraj', en: 'Navigate', de: 'Navigieren', it: 'Naviga' },
  'action.report': { hr: 'Prijavi netočne podatke', en: 'Report incorrect info', de: 'Falsche Info melden', it: 'Segnala informazioni errate' },
  'action.claimOwner': { hr: 'Ja sam vlasnik', en: 'I am the owner', de: 'Ich bin der Besitzer', it: 'Sono il proprietario' },
  'action.filter.openNow': { hr: 'Otvoreno sada', en: 'Open now', de: 'Jetzt geöffnet', it: 'Aperto ora' },
  'action.back': { hr: 'Natrag', en: 'Back', de: 'Zurück', it: 'Indietro' },
  'category.pharmacy': { hr: 'Ljekarna', en: 'Pharmacy', de: 'Apotheke', it: 'Farmacia' },
  'category.doctor': { hr: 'Zdravstvo', en: 'Health', de: 'Gesundheit', it: 'Salute' },
  'category.dentist': { hr: 'Dentalna medicina', en: 'Dental', de: 'Zahnmedizin', it: 'Odontoiatria' },
  'category.medicine': { hr: 'Opća medicina', en: 'General medicine', de: 'Allgemeinmedizin', it: 'Medicina generale' },
  'category.specialist': { hr: 'Specijalistička', en: 'Specialist', de: 'Fachärzte', it: 'Specialisti' },
  'category.hospital': { hr: 'Bolnica', en: 'Hospital', de: 'Krankenhaus', it: 'Ospedale' },
  'health.subAll': { hr: 'Sve', en: 'All', de: 'Alle', it: 'Tutti' },
  'health.subGeneral': { hr: 'Opća', en: 'General', de: 'Allgemein', it: 'Generale' },
  'health.subDental': { hr: 'Dentalna', en: 'Dental', de: 'Zahn', it: 'Dentale' },
  'health.subSpecialist': { hr: 'Specijalistička', en: 'Specialist', de: 'Facharzt', it: 'Specialista' },
  'health.subHospital': { hr: 'Bolnica', en: 'Hospital', de: 'Krankenhaus', it: 'Ospedale' },
  'health.inPreparation': { hr: 'Podaci u pripremi — provjeri prije dolaska', en: 'Data in preparation — verify before visiting', de: 'Daten in Vorbereitung — vor Besuch prüfen', it: 'Dati in preparazione — verifica prima' },
  'category.shops': { hr: 'Trgovine', en: 'Shops', de: 'Geschäfte', it: 'Negozi' },
  'category.restaurants': { hr: 'Restorani', en: 'Restaurants', de: 'Restaurants', it: 'Ristoranti' },
  'category.cafes': { hr: 'Kafići', en: 'Cafes', de: 'Cafés', it: 'Caffè' },
  'category.gas': { hr: 'Benzinska', en: 'Gas Station', de: 'Tankstelle', it: 'Distributore' },
  'category.nauticalGas': { hr: 'Nautičke', en: 'Nautical Gas', de: 'Nautik-Tankstelle', it: 'Distributore nautico' },
  'category.parking': { hr: 'Parking', en: 'Parking', de: 'Parken', it: 'Parcheggio' },
  'category.transport': { hr: 'Prijevoz', en: 'Transport', de: 'Transport', it: 'Trasporti' },
  'category.emergency': { hr: 'Hitno', en: 'Emergency', de: 'Notfall', it: 'Emergenza' },
  'category.events': { hr: 'Događanja', en: 'Events', de: 'Veranstaltungen', it: 'Eventi' },
  'category.publicServices': { hr: 'Javne službe', en: 'Public Services', de: 'Öffentliche Dienste', it: 'Servizi Pubblici' },
  'detail.workingHours': { hr: 'Radno vrijeme', en: 'Working Hours', de: 'Öffnungszeiten', it: 'Orario di lavoro' },
  'detail.contact': { hr: 'Kontakt', en: 'Contact', de: 'Kontakt', it: 'Contatto' },
  'detail.lastVerified': { hr: 'Zadnja provjera', en: 'Last verified', de: 'Zuletzt überprüft', it: 'Ultima verifica' },
  'report.title': { hr: 'Prijavi problem', en: 'Report Issue', de: 'Problem melden', it: 'Segnala problema' },
  'report.closed': { hr: 'Zatvoreno', en: 'Closed', de: 'Geschlossen', it: 'Chiuso' },
  'report.moved': { hr: 'Preselio', en: 'Moved', de: 'Umgezogen', it: 'Trasferito' },
  'report.wrongHours': { hr: 'Krivo radno vrijeme', en: 'Wrong hours', de: 'Falsche Öffnungszeiten', it: 'Orario errato' },
  'report.phoneIncorrect': { hr: 'Pogrešan telefon', en: 'Phone incorrect', de: 'Telefon falsch', it: 'Telefono errato' },
  'report.thanks': { hr: 'Hvala na prijavi!', en: 'Thanks for reporting!', de: 'Danke für die Meldung!', it: 'Grazie per la segnalazione!' },
  'claim.title': { hr: 'Preuzmi vlasništvo', en: 'Claim Ownership', de: 'Eigentum beanspruchen', it: 'Rivendica proprietà' },
  'claim.email': { hr: 'Vaš email', en: 'Your email', de: 'Ihre E-Mail', it: 'La tua email' },
  'claim.code': { hr: 'Unesite kod', en: 'Enter code', de: 'Code eingeben', it: 'Inserisci codice' },
  'claim.verify': { hr: 'Potvrdi', en: 'Verify', de: 'Bestätigen', it: 'Verifica' },
  'claim.codeSent': { hr: 'Kod poslan na email!', en: 'Code sent to email!', de: 'Code an E-Mail gesendet!', it: 'Codice inviato via email!' },
  'claim.submit': { hr: 'Pošalji zahtjev', en: 'Submit request', de: 'Anfrage senden', it: 'Invia richiesta' },
  'claim.success': { hr: 'Verificirano! Možete uređivati podatke.', en: 'Verified! You can now edit info.', de: 'Verifiziert! Sie können Infos bearbeiten.', it: 'Verificato! Puoi modificare le info.' },
  'claim.loginRequired': { hr: 'Morate biti prijavljeni za preuzimanje vlasništva.', en: 'You must be logged in to claim ownership.', de: 'Sie müssen angemeldet sein.', it: 'Devi essere connesso.' },
  'claim.sending': { hr: 'Šaljem kod...', en: 'Sending code...', de: 'Code wird gesendet...', it: 'Invio codice...' },
  'claim.verifying': { hr: 'Provjeravam...', en: 'Verifying...', de: 'Überprüfe...', it: 'Verifica...' },
  'claim.error': { hr: 'Došlo je do greške. Pokušajte ponovno.', en: 'An error occurred. Please try again.', de: 'Ein Fehler ist aufgetreten.', it: 'Si è verificato un errore.' },
  'claim.tooMany': { hr: 'Previše pokušaja. Pokušajte kasnije.', en: 'Too many attempts. Try later.', de: 'Zu viele Versuche.', it: 'Troppi tentativi.' },
  'claim.expired': { hr: 'Kod je istekao. Zatražite novi.', en: 'Code expired. Request a new one.', de: 'Code abgelaufen.', it: 'Codice scaduto.' },
  'claim.locked': { hr: 'Zahtjev zaključan. Pokušajte za 30 min.', en: 'Request locked. Try in 30 min.', de: 'Anfrage gesperrt. 30 Min warten.', it: 'Richiesta bloccata. Riprova tra 30 min.' },
  'emergency.title': { hr: 'Hitni brojevi', en: 'Emergency Numbers', de: 'Notfallnummern', it: 'Numeri di emergenza' },
  'emergency.police': { hr: 'Policija', en: 'Police', de: 'Polizei', it: 'Polizia' },
  'emergency.ambulance': { hr: 'Hitna pomoć', en: 'Ambulance', de: 'Krankenwagen', it: 'Ambulanza' },
  'emergency.fire': { hr: 'Vatrogasci', en: 'Fire Department', de: 'Feuerwehr', it: 'Vigili del fuoco' },
  'emergency.hospital': { hr: 'Bolnica', en: 'Hospital', de: 'Krankenhaus', it: 'Ospedale' },
  'emergency.touristPolice': { hr: 'Turistička policija', en: 'Tourist Police', de: 'Touristenpolizei', it: 'Polizia turistica' },
  'home.trending': { hr: 'Popularno', en: 'Trending', de: 'Beliebt', it: 'Di tendenza' },
  'home.nearby': { hr: 'U blizini', en: 'Nearby', de: 'In der Nähe', it: 'Nelle vicinanze' },
  'days.mon': { hr: 'Pon', en: 'Mon', de: 'Mo', it: 'Lun' },
  'days.tue': { hr: 'Uto', en: 'Tue', de: 'Di', it: 'Mar' },
  'days.wed': { hr: 'Sri', en: 'Wed', de: 'Mi', it: 'Mer' },
  'days.thu': { hr: 'Čet', en: 'Thu', de: 'Do', it: 'Gio' },
  'days.fri': { hr: 'Pet', en: 'Fri', de: 'Fr', it: 'Ven' },
  'days.sat': { hr: 'Sub', en: 'Sat', de: 'Sa', it: 'Sab' },
  'days.sun': { hr: 'Ned', en: 'Sun', de: 'So', it: 'Dom' },
  // Trust layer
  'trust.ownerVerified': { hr: 'Vlasnik verificirao', en: 'Owner verified', de: 'Vom Inhaber verifiziert', it: 'Verificato dal proprietario' },
  'trust.communityConfirmed': { hr: 'Zajednica potvrdila', en: 'Community confirmed', de: 'Gemeinschaft bestätigt', it: 'Confermato dalla comunità' },
  'trust.unverified': { hr: 'Nepotvrđeno', en: 'Unverified', de: 'Nicht verifiziert', it: 'Non verificato' },
  'trust.possiblyIncorrect': { hr: 'Moguće netočno', en: 'Possibly incorrect', de: 'Möglicherweise falsch', it: 'Possibilmente errato' },
  'trust.score': { hr: 'Ocjena pouzdanosti', en: 'Trust score', de: 'Vertrauenswert', it: 'Punteggio di fiducia' },
  'trust.lastOwner': { hr: 'Vlasnik potvrdio', en: 'Owner confirmed', de: 'Inhaber bestätigt', it: 'Proprietario confermato' },
  'trust.lastCommunity': { hr: 'Zajednica potvrdila', en: 'Community confirmed', de: 'Gemeinschaft bestätigt', it: 'Comunità confermata' },
  'trust.autoChecked': { hr: 'Automatski provjereno danas', en: 'Automatically checked today', de: 'Heute automatisch geprüft', it: 'Controllato automaticamente oggi' },
  'trust.dataReliability': { hr: 'Pouzdanost podataka', en: 'Data reliability', de: 'Datenzuverlässigkeit', it: 'Affidabilità dati' },
  'trust.warningHidden': { hr: 'Status skriven — previše prijava', en: 'Status hidden — too many reports', de: 'Status verborgen — zu viele Meldungen', it: 'Stato nascosto — troppe segnalazioni' },
  // Field report
  'field.iAmHere': { hr: 'Ja sam ovdje', en: 'I am here now', de: 'Ich bin hier', it: 'Sono qui ora' },
  'field.title': { hr: 'Potvrdi iz terena', en: 'Report from field', de: 'Vor-Ort-Bericht', it: 'Segnala dal campo' },
  'field.subtitle': { hr: 'Potvrdi je li otvoreno ili zatvoreno', en: 'Confirm if open or closed', de: 'Bestätigen ob geöffnet oder geschlossen', it: 'Conferma se aperto o chiuso' },
  'field.thanks': { hr: 'Hvala!', en: 'Thanks!', de: 'Danke!', it: 'Grazie!' },
  // Dashboard
  'dashboard.today': { hr: 'Danas u Zadru', en: 'Today in Zadar', de: 'Heute in Zadar', it: 'Oggi a Zara' },
  'dashboard.sea': { hr: 'More', en: 'Sea', de: 'Meer', it: 'Mare' },
  'dashboard.sunset': { hr: 'Zalazak', en: 'Sunset', de: 'Sonnenuntergang', it: 'Tramonto' },
  'dashboard.crowd': { hr: 'Stari grad', en: 'Old town', de: 'Altstadt', it: 'Centro storico' },
  'dashboard.parking': { hr: 'Parking', en: 'Parking', de: 'Parken', it: 'Parcheggio' },
  'dashboard.alerts': { hr: 'Obavijesti danas', en: 'Today Alerts', de: 'Meldungen heute', it: 'Avvisi oggi' },
  'dashboard.quickActions': { hr: 'Brze radnje', en: 'Quick Actions', de: 'Schnellaktionen', it: 'Azioni rapide' },
  'weather.sunny': { hr: 'Sunčano', en: 'Sunny', de: 'Sonnig', it: 'Soleggiato' },
  'weather.clear_night': { hr: 'Vedro', en: 'Clear', de: 'Klar', it: 'Sereno' },
  'weather.partly_cloudy': { hr: 'Djelomično oblačno', en: 'Partly cloudy', de: 'Teilweise bewölkt', it: 'Parzialmente nuvoloso' },
  'weather.foggy': { hr: 'Maglovito', en: 'Foggy', de: 'Nebelig', it: 'Nebbioso' },
  'weather.rainy': { hr: 'Kišovito', en: 'Rainy', de: 'Regnerisch', it: 'Piovoso' },
  'weather.snowy': { hr: 'Snježno', en: 'Snowy', de: 'Schnee', it: 'Nevoso' },
  'weather.stormy': { hr: 'Olujno', en: 'Stormy', de: 'Stürmisch', it: 'Tempestoso' },
  'wind.calm': { hr: 'Mirno', en: 'Calm', de: 'Ruhig', it: 'Calmo' },
  'wind.moderate': { hr: 'Umjereno', en: 'Moderate', de: 'Mäßig', it: 'Moderato' },
  'wind.bura': { hr: 'Bura', en: 'Bura wind', de: 'Bura-Wind', it: 'Bora' },
  'wind.jugo': { hr: 'Jugo', en: 'Jugo wind', de: 'Jugo-Wind', it: 'Scirocco' },
  'crowd.low': { hr: 'Malo', en: 'Low', de: 'Wenig', it: 'Basso' },
  'crowd.medium': { hr: 'Srednje', en: 'Medium', de: 'Mittel', it: 'Medio' },
  'crowd.high': { hr: 'Puno', en: 'Busy', de: 'Voll', it: 'Affollato' },
  'parking.easy': { hr: 'Lako', en: 'Easy', de: 'Einfach', it: 'Facile' },
  'parking.normal': { hr: 'Normalno', en: 'Normal', de: 'Normal', it: 'Normale' },
  'parking.full': { hr: 'Puno', en: 'Full', de: 'Voll', it: 'Pieno' },
  'parking.free': { hr: 'Besplatno', en: 'Free', de: 'Kostenlos', it: 'Gratuito' },
  'parking.paid': { hr: 'Naplata', en: 'Paid', de: 'Gebühr', it: 'A pagamento' },
  // Alerts
  'alert.dutyPharmacy': { hr: 'Dežurna ljekarna', en: 'Pharmacy on duty', de: 'Dienstapotheke', it: 'Farmacia di turno' },
  'alert.dutyPharmacyDesc': { hr: 'Ljekarna Centar - Jadran, Put Murvice 2', en: 'Ljekarna Centar - Jadran, Put Murvice 2', de: 'Ljekarna Centar - Jadran, Put Murvice 2', it: 'Ljekarna Centar - Jadran, Put Murvice 2' },
  'alert.roadClosed': { hr: 'Cesta zatvorena', en: 'Road closed', de: 'Straße gesperrt', it: 'Strada chiusa' },
  'alert.roadClosedDesc': { hr: 'Široka ulica — radovi do 18h', en: 'Široka ulica — works until 6 PM', de: 'Široka ulica — Bauarbeiten bis 18 Uhr', it: 'Široka ulica — lavori fino alle 18' },
  'alert.eventTonight': { hr: 'Događanje večeras', en: 'Event tonight', de: 'Event heute Abend', it: 'Evento stasera' },
  'alert.eventTonightDesc': { hr: 'Glazbeni večer na Forumu, 20:00', en: 'Music night at Forum, 8 PM', de: 'Musikabend am Forum, 20 Uhr', it: 'Serata musicale al Foro, 20:00' },
  'alert.strongWind': { hr: 'Jak vjetar', en: 'Strong wind', de: 'Starker Wind', it: 'Vento forte' },
  'alert.strongWindDesc': { hr: 'Bura — udari do 55 km/h', en: 'Bura — gusts up to 55 km/h', de: 'Bura — Böen bis 55 km/h', it: 'Bora — raffiche fino a 55 km/h' },
  'alert.powerOutage': { hr: 'Nestanak struje', en: 'Power outage', de: 'Stromausfall', it: 'Interruzione di corrente' },
  'alert.powerOutageDesc': { hr: '{area} — {time}', en: '{area} — {time}', de: '{area} — {time}', it: '{area} — {time}' },
  'alert.powerOutageMultiple': { hr: '{count} područja bez struje danas', en: '{count} areas without power today', de: '{count} Gebiete ohne Strom heute', it: '{count} aree senza corrente oggi' },
  'alert.waterOutage': { hr: 'Bez vode', en: 'Water outage', de: 'Wasserausfall', it: 'Interruzione idrica' },
  'alert.waterOutageMultiple': { hr: '{count} područja bez vode danas', en: '{count} areas without water today', de: '{count} Gebiete ohne Wasser heute', it: '{count} aree senza acqua oggi' },
  // Quick actions
  'quick.pharmacyNow': { hr: 'Ljekarna', en: 'Pharmacy', de: 'Apotheke', it: 'Farmacia' },
  'quick.freeParking': { hr: 'Parking', en: 'Parking', de: 'Parken', it: 'Parcheggio' },
  'quick.emergency': { hr: 'Hitno', en: 'Emergency', de: 'Notfall', it: 'Emergenza' },
  'quick.bus': { hr: 'Autobus', en: 'Bus', de: 'Bus', it: 'Autobus' },
  'quick.cinema': { hr: 'Kino', en: 'Cinema', de: 'Kino', it: 'Cinema' },
  'quick.digital': { hr: 'e-Usluge', en: 'e-Services', de: 'e-Dienste', it: 'e-Servizi' },
  // Tourist quick actions
  'tourist.explore': { hr: 'Istraži Zadar', en: 'Explore Zadar', de: 'Zadar entdecken', it: 'Esplora Zara' },
  'tourist.beaches': { hr: 'Plaže', en: 'Beaches', de: 'Strände', it: 'Spiagge' },
  'tourist.sights': { hr: 'Znamenitosti', en: 'Sightseeing', de: 'Sehenswürdigkeiten', it: 'Attrazioni' },
  'tourist.quest': { hr: 'Zadar Quest', en: 'Zadar Quest', de: 'Zadar Quest', it: 'Zadar Quest' },
  'tourist.restaurants': { hr: 'Restorani', en: 'Restaurants', de: 'Restaurants', it: 'Ristoranti' },
  // For you
  'foryou.morning': { hr: 'Za tebe ujutro', en: 'For you this morning', de: 'Für dich am Morgen', it: 'Per te stamattina' },
  'foryou.noon': { hr: 'Za ručak u blizini', en: 'Lunch nearby', de: 'Mittagessen in der Nähe', it: 'Pranzo nelle vicinanze' },
  'foryou.evening': { hr: 'Za večeras', en: 'For your evening', de: 'Für deinen Abend', it: 'Per la tua serata' },
  'foryou.night': { hr: 'Noćne usluge', en: 'Night services', de: 'Nachtdienste', it: 'Servizi notturni' },
  // Business side
  'biz.panel': { hr: 'Panel vlasnika', en: 'Owner Panel', de: 'Inhaberbereich', it: 'Pannello proprietario' },
  'biz.analytics': { hr: 'Statistika danas', en: 'Today\'s analytics', de: 'Heutige Statistik', it: 'Statistiche di oggi' },
  'biz.views': { hr: 'Pregledi', en: 'Views', de: 'Aufrufe', it: 'Visualizzazioni' },
  'biz.calls': { hr: 'Pozivi', en: 'Calls', de: 'Anrufe', it: 'Chiamate' },
  'biz.navClicks': { hr: 'Navigacija', en: 'Navigate', de: 'Navigation', it: 'Navigazione' },
  'biz.setOccupancy': { hr: 'Postavite zauzetost', en: 'Set occupancy', de: 'Auslastung einstellen', it: 'Imposta occupazione' },
  'biz.occupancy.quiet': { hr: 'Mirno', en: 'Quiet', de: 'Ruhig', it: 'Tranquillo' },
  'biz.occupancy.normal': { hr: 'Normalno', en: 'Normal', de: 'Normal', it: 'Normale' },
  'biz.occupancy.busy': { hr: 'Gužva', en: 'Busy', de: 'Voll', it: 'Affollato' },
  'biz.dailyOffer': { hr: 'Dnevna ponuda', en: 'Daily offer', de: 'Tagesangebot', it: 'Offerta del giorno' },
  'biz.dailyOfferPlaceholder': { hr: 'npr. 20% popusta na kavu', en: 'e.g. 20% off coffee', de: 'z.B. 20% Rabatt auf Kaffee', it: 'es. 20% di sconto sul caffè' },
  'biz.announcement': { hr: 'Obavijest', en: 'Announcement', de: 'Ankündigung', it: 'Annuncio' },
  'biz.announcementPlaceholder': { hr: 'Napišite poruku za korisnike…', en: 'Write a message for customers…', de: 'Nachricht für Kunden…', it: 'Scrivi un messaggio per i clienti…' },
  'biz.corrections': { hr: 'Korekture zajednice', en: 'Community corrections', de: 'Gemeinschafts-Korrekturen', it: 'Correzioni della comunità' },
  'biz.reportsReceived': { hr: 'prijava primljeno', en: 'reports received', de: 'Meldungen erhalten', it: 'segnalazioni ricevute' },
  'biz.respondToReports': { hr: 'Odgovori na prijave', en: 'Respond to reports', de: 'Auf Meldungen antworten', it: 'Rispondi alle segnalazioni' },
  'biz.noReports': { hr: 'Nema prijava — sve je u redu!', en: 'No reports — all good!', de: 'Keine Meldungen — alles gut!', it: 'Nessuna segnalazione — tutto bene!' },
  'biz.saveChanges': { hr: 'Spremi promjene', en: 'Save changes', de: 'Änderungen speichern', it: 'Salva modifiche' },
  'biz.saved': { hr: 'Spremljeno!', en: 'Saved!', de: 'Gespeichert!', it: 'Salvato!' },
  'biz.trustExplain.title': { hr: 'Kako radi vidljivost?', en: 'How does visibility work?', de: 'Wie funktioniert die Sichtbarkeit?', it: 'Come funziona la visibilità?' },
  'biz.trustExplain.body': { hr: 'Verificirani i aktivni profili pojavljuju se više u rezultatima. Neaktivni profili padaju niže. Nema plaćenog rangiranja — samo aktivnost.', en: 'Verified and active profiles appear higher in results. Inactive profiles rank lower. No paid ranking — only activity matters.', de: 'Verifizierte und aktive Profile erscheinen höher. Inaktive Profile sinken. Kein bezahltes Ranking — nur Aktivität zählt.', it: 'I profili verificati e attivi appaiono più in alto. I profili inattivi scendono. Nessun posizionamento a pagamento — conta solo l\'attività.' },
  'biz.forCustomers': { hr: 'Za korisnike danas', en: 'For customers today', de: 'Für Kunden heute', it: 'Per i clienti oggi' },
  'biz.liveOccupancy': { hr: 'Zauzetost', en: 'Live occupancy', de: 'Aktuelle Auslastung', it: 'Occupazione live' },
  'biz.waitTime': { hr: 'Vrijeme čekanja', en: 'Wait time', de: 'Wartezeit', it: 'Tempo di attesa' },
  'biz.nextAppt': { hr: 'Sljedeći termin', en: 'Next available', de: 'Nächster Termin', it: 'Prossimo disponibile' },
  // Mode switch
  'mode.resident': { hr: 'Rezident', en: 'Resident', de: 'Einwohner', it: 'Residente' },
  'mode.tourist': { hr: 'Turist', en: 'Tourist', de: 'Tourist', it: 'Turista' },
  // Featured
  'featured.title': { hr: 'Istaknuto u blizini', en: 'Featured today nearby', de: 'Empfohlen in der Nähe', it: 'In evidenza oggi vicino' },
  // Follow/notify
  'follow.notify': { hr: 'Obavijesti me', en: 'Notify me', de: 'Benachrichtigen', it: 'Avvisami' },
  'follow.following': { hr: 'Pratim', en: 'Following', de: 'Folge ich', it: 'Seguo' },
  'follow.options': { hr: 'Kada te obavijestiti?', en: 'When to notify you?', de: 'Wann benachrichtigen?', it: 'Quando avvisarti?' },
  'follow.whenOpens': { hr: 'Kad se otvori', en: 'When it opens', de: 'Wenn es öffnet', it: 'Quando apre' },
  'follow.whenQuiet': { hr: 'Kad bude mirno', en: 'When not crowded', de: 'Wenn nicht voll', it: 'Quando non è affollato' },
  'follow.newOffer': { hr: 'Nova ponuda', en: 'New offer', de: 'Neues Angebot', it: 'Nuova offerta' },
  // For business page
  'forbiz.title': { hr: 'Za tvrtke', en: 'For Businesses', de: 'Für Unternehmen', it: 'Per le aziende' },
  'forbiz.hero.title': { hr: 'Pridružite se ZadarIQ', en: 'Join ZadarIQ', de: 'Treten Sie ZadarIQ bei', it: 'Unisciti a ZadarIQ' },
  'forbiz.hero.subtitle': { hr: 'Besplatno upravljajte profilom, povećajte vidljivost i izgradite povjerenje.', en: 'Manage your profile for free, increase visibility, and build trust.', de: 'Verwalten Sie Ihr Profil kostenlos, erhöhen Sie die Sichtbarkeit und bauen Sie Vertrauen auf.', it: 'Gestisci il tuo profilo gratuitamente, aumenta la visibilità e costruisci fiducia.' },
  'forbiz.benefit1.title': { hr: 'Verificirani profil', en: 'Verified profile', de: 'Verifiziertes Profil', it: 'Profilo verificato' },
  'forbiz.benefit1.desc': { hr: 'Zelena oznaka — korisnici znaju da su podaci točni.', en: 'Green badge — users know your data is accurate.', de: 'Grünes Abzeichen — Nutzer wissen, dass Ihre Daten korrekt sind.', it: 'Badge verde — gli utenti sanno che i dati sono accurati.' },
  'forbiz.benefit2.title': { hr: 'Statistika u stvarnom vremenu', en: 'Real-time analytics', de: 'Echtzeit-Statistiken', it: 'Statistiche in tempo reale' },
  'forbiz.benefit2.desc': { hr: 'Vidite koliko korisnika vas gleda, zove i navigira svaki dan.', en: 'See how many users view, call, and navigate to you daily.', de: 'Sehen Sie, wie viele Nutzer Sie täglich aufrufen, anrufen und zu Ihnen navigieren.', it: 'Scopri quanti utenti ti visualizzano, chiamano e navigano ogni giorno.' },
  'forbiz.benefit3.title': { hr: 'Objavite ponude', en: 'Publish offers', de: 'Angebote veröffentlichen', it: 'Pubblica offerte' },
  'forbiz.benefit3.desc': { hr: 'Dnevne ponude i obavijesti vidljive svim korisnicima.', en: 'Daily offers and announcements visible to all users.', de: 'Tagesangebote und Ankündigungen für alle Nutzer sichtbar.', it: 'Offerte giornaliere e annunci visibili a tutti gli utenti.' },
  'forbiz.benefit4.title': { hr: 'Odgovorite na korekcije', en: 'Respond to corrections', de: 'Auf Korrekturen antworten', it: 'Rispondi alle correzioni' },
  'forbiz.benefit4.desc': { hr: 'Vidite prijave korisnika i brzo ispravite podatke.', en: 'See user reports and quickly fix your data.', de: 'Sehen Sie Nutzermeldungen und korrigieren Sie Ihre Daten schnell.', it: 'Vedi le segnalazioni degli utenti e correggi rapidamente i dati.' },
  'forbiz.benefit5.title': { hr: 'Viša pozicija', en: 'Higher ranking', de: 'Höheres Ranking', it: 'Posizionamento migliore' },
  'forbiz.benefit5.desc': { hr: 'Aktivni profili pojavljuju se više — bez plaćenog oglašavanja.', en: 'Active profiles appear higher — no paid advertising needed.', de: 'Aktive Profile erscheinen höher — keine bezahlte Werbung nötig.', it: 'I profili attivi appaiono più in alto — nessuna pubblicità a pagamento.' },
  'forbiz.benefit6.title': { hr: 'Više od Google Mapsa', en: 'Better than Google Maps', de: 'Besser als Google Maps', it: 'Meglio di Google Maps' },
  'forbiz.benefit6.desc': { hr: 'Korisnici ovdje dobivaju ažurne, provjerene podatke — a ne zastarjele.', en: 'Users here get up-to-date, verified data — not outdated info.', de: 'Nutzer erhalten hier aktuelle, verifizierte Daten — keine veralteten Infos.', it: 'Gli utenti qui trovano dati aggiornati e verificati — non informazioni obsolete.' },
  'forbiz.trustEconomy.title': { hr: 'Ekonomija povjerenja', en: 'Trust + Visibility Economy', de: 'Vertrauens-Ökonomie', it: 'Economia della fiducia' },
  'forbiz.trustEconomy.rule1': { hr: 'Verificirani profili pojavljuju se više u rezultatima.', en: 'Verified profiles appear higher in results.', de: 'Verifizierte Profile erscheinen höher in den Ergebnissen.', it: 'I profili verificati appaiono più in alto nei risultati.' },
  'forbiz.trustEconomy.rule2': { hr: 'Neaktivni profili padaju niže.', en: 'Inactive profiles rank lower.', de: 'Inaktive Profile sinken in den Ergebnissen.', it: 'I profili inattivi scendono nei risultati.' },
  'forbiz.trustEconomy.rule3': { hr: 'Nema plaćenog rangiranja — samo aktivnost i pouzdanost.', en: 'No paid ranking — only activity and reliability.', de: 'Kein bezahltes Ranking — nur Aktivität und Zuverlässigkeit.', it: 'Nessun posizionamento a pagamento — solo attività e affidabilità.' },
  'forbiz.cta': { hr: 'Preuzmi svoj profil', en: 'Claim your profile', de: 'Profil beanspruchen', it: 'Rivendica il tuo profilo' },
  'forbiz.free': { hr: 'Potpuno besplatno.', en: 'Completely free.', de: 'Komplett kostenlos. Für immer.', it: 'Completamente gratuito.' },
  // Public services
  'publicServices.title': { hr: 'Javne službe', en: 'Public Services', de: 'Öffentliche Dienste', it: 'Servizi Pubblici' },
  'publicServices.subtitle': { hr: 'Gradske institucije i službe', en: 'City institutions & services', de: 'Städtische Institutionen & Dienste', it: 'Istituzioni e servizi comunali' },
  'publicServices.gradZadar': { hr: 'Grad Zadar', en: 'City of Zadar', de: 'Stadt Zadar', it: 'Città di Zara' },
  'publicServices.zadarskaZupanija': { hr: 'Zadarska županija', en: 'Zadar County', de: 'Gespanschaft Zadar', it: 'Contea di Zara' },
  'publicServices.centrala': { hr: 'Centrala', en: 'Switchboard', de: 'Zentrale', it: 'Centralino' },
  'publicServices.departments': { hr: 'Upravni odjeli i stručne službe', en: 'Administrative departments', de: 'Verwaltungsabteilungen', it: 'Dipartimenti amministrativi' },
  // Utility companies
  'utilities.menuLabel': { hr: 'Komunalne tvrtke', en: 'Utility Companies', de: 'Versorgungsunternehmen', it: 'Aziende di servizi' },
  'utilities.title': { hr: 'Komunalne tvrtke', en: 'Utility Companies', de: 'Versorgungsunternehmen', it: 'Aziende di servizi' },
  'utilities.subtitle': { hr: 'Čistoća, Vodovod, HEP', en: 'Waste, Water, Electricity', de: 'Abfall, Wasser, Strom', it: 'Rifiuti, Acqua, Elettricità' },
  'utilities.emergency': { hr: 'Hitno', en: 'Emergency', de: 'Notfall', it: 'Emergenza' },
  'utilities.services': { hr: 'Usluge', en: 'Services', de: 'Dienste', it: 'Servizi' },
  // Transport
  'quick.transport': { hr: 'Javni prijevoz', en: 'Public transport', de: 'Öffentl. Verkehr', it: 'Trasporto pubblico' },
  'transport.title': { hr: 'Prijevoz', en: 'Transport', de: 'Transport', it: 'Trasporti' },
  'transport.subtitle': { hr: 'Trajekti, autobusi i više', en: 'Ferries, buses & more', de: 'Fähren, Busse & mehr', it: 'Traghetti, autobus e altro' },
  'transport.ferries': { hr: 'Trajekti', en: 'Ferries', de: 'Fähren', it: 'Traghetti' },
  'transport.catamarans': { hr: 'Katamarani', en: 'Catamarans', de: 'Katamarane', it: 'Catamarani' },
  'transport.cityBus': { hr: 'Gradski bus', en: 'City Bus', de: 'Stadtbus', it: 'Bus urbano' },
  'transport.intercity': { hr: 'Međugradski', en: 'Intercity', de: 'Überlandbus', it: 'Intercity' },
  'transport.boarding': { hr: 'Ukrcaj', en: 'Boarding', de: 'Einstieg', it: 'Imbarco' },
  'transport.scheduled': { hr: 'Planirano', en: 'Scheduled', de: 'Geplant', it: 'Pianificato' },
  'transport.delayed': { hr: 'Kasni', en: 'Delayed', de: 'Verspätet', it: 'In ritardo' },
  'transport.closed': { hr: 'Zatvoren', en: 'Closed', de: 'Geschlossen', it: 'Chiuso' },
  'transport.nextFrom': { hr: 'Sljedeći polasci iz', en: 'Next departures from', de: 'Nächste Abfahrten von', it: 'Prossime partenze da' },
  'transport.fastLines': { hr: 'Brze linije', en: 'Fast lines', de: 'Schnelllinien', it: 'Linee veloci' },
  'transport.selectLine': { hr: 'Odaberi liniju', en: 'Select line', de: 'Linie wählen', it: 'Seleziona linea' },
  'transport.useLocation': { hr: 'Moja lokacija', en: 'My location', de: 'Mein Standort', it: 'La mia posizione' },
  'transport.nearestStop': { hr: 'Najbliža stanica', en: 'Nearest stop', de: 'Nächste Haltestelle', it: 'Fermata più vicina' },
  'transport.nextDepartures': { hr: 'Sljedeći polasci', en: 'Next departures', de: 'Nächste Abfahrten', it: 'Prossime partenze' },
  'transport.noMore': { hr: 'Nema više polazaka danas', en: 'No more departures today', de: 'Keine Abfahrten mehr heute', it: 'Nessuna partenza oggi' },
  'transport.searchDestination': { hr: 'Pretraži destinaciju…', en: 'Search destination…', de: 'Ziel suchen…', it: 'Cerca destinazione…' },
  'transport.platform': { hr: 'Peron', en: 'Platform', de: 'Gleis', it: 'Banchina' },
  'transport.noResults': { hr: 'Nema rezultata', en: 'No results', de: 'Keine Ergebnisse', it: 'Nessun risultato' },
  'search.noResults': { hr: 'Nema rezultata', en: 'No results found', de: 'Keine Ergebnisse', it: 'Nessun risultato' },
  'search.clearFilter': { hr: 'Ukloni filter', en: 'Clear filter', de: 'Filter entfernen', it: 'Rimuovi filtro' },
  'transport.line': { hr: 'Linija', en: 'Line', de: 'Linie', it: 'Linea' },
  'transport.widget': { hr: 'Prijevoz uskoro', en: 'Transport soon', de: 'Transport bald', it: 'Trasporti a breve' },
  'transport.cachedToday': { hr: 'Offline spremno', en: 'Cached today', de: 'Heute gespeichert', it: 'Salvato oggi' },
  // Clock
  'clock.zadarTime': { hr: 'Zadar', en: 'Zadar time', de: 'Zadar-Zeit', it: 'Ora di Zara' },
  // Now in Zadar
  'now.title': { hr: 'Sada u Zadru', en: 'Now in Zadar', de: 'Jetzt in Zadar', it: 'Ora a Zara' },
  'now.pharmacy': { hr: 'Dežurna ljekarna', en: 'Duty pharmacy', de: 'Dienstapotheke', it: 'Farmacia di turno' },
  'now.emergencyMedical': { hr: 'Hitna pomoć', en: 'Emergency', de: 'Notfall', it: 'Emergenza' },
  'now.emergencyMedicalAnswer': { hr: '112 · Hitna medicinska pomoć', en: '112 · Emergency medical', de: '112 · Notarzt', it: '112 · Emergenza medica' },
  'now.nextFerry': { hr: 'Sljedeći trajekt', en: 'Next ferry', de: 'Nächste Fähre', it: 'Prossimo traghetto' },
  'now.noFerry': { hr: 'Nema polazaka danas', en: 'No departures today', de: 'Keine Abfahrten heute', it: 'Nessuna partenza oggi' },
  'now.parking': { hr: 'Parking poluotok', en: 'Peninsula parking', de: 'Halbinsel Parken', it: 'Parcheggio penisola' },
  'now.parkingFree': { hr: 'Besplatno sada', en: 'Free now', de: 'Jetzt kostenlos', it: 'Gratuito ora' },
  'now.parkingPaid': { hr: 'Naplata aktivna', en: 'Paid now', de: 'Gebührenpflichtig', it: 'A pagamento' },
  'now.weather': { hr: 'Vrijeme sada', en: 'Weather now', de: 'Wetter jetzt', it: 'Meteo ora' },
  'now.sunset': { hr: 'Zalazak sunca', en: 'Sunset', de: 'Sonnenuntergang', it: 'Tramonto' },
  'now.powerOutage': { hr: 'Nestanak struje', en: 'Power outage', de: 'Stromausfall', it: 'Interruzione corrente' },
  'now.waterOutage': { hr: 'Bez vode', en: 'Water outage', de: 'Wasserausfall', it: 'Interruzione idrica' },
  'now.areasAffected': { hr: 'područja', en: 'areas', de: 'Gebiete', it: 'aree' },
  'now.sunrise': { hr: 'Izlazak sunca', en: 'Sunrise', de: 'Sonnenaufgang', it: 'Alba' },
  'now.meteoAlert': { hr: 'Meteo upozorenje', en: 'Weather alert', de: 'Wetterwarnung', it: 'Allerta meteo' },
  'meteo.type.wind': { hr: 'Jak vjetar', en: 'Strong wind', de: 'Starker Wind', it: 'Vento forte' },
  'meteo.type.rain': { hr: 'Obilna kiša', en: 'Heavy rain', de: 'Starkregen', it: 'Pioggia intensa' },
  'meteo.type.thunderstorm': { hr: 'Grmljavina', en: 'Thunderstorm', de: 'Gewitter', it: 'Temporale' },
  'meteo.type.snow': { hr: 'Snijeg', en: 'Snow', de: 'Schnee', it: 'Neve' },
  'meteo.type.fog': { hr: 'Magla', en: 'Fog', de: 'Nebel', it: 'Nebbia' },
  'meteo.type.extreme_heat': { hr: 'Toplinski val', en: 'Heat wave', de: 'Hitzewelle', it: 'Ondata di calore' },
  'meteo.type.extreme_cold': { hr: 'Jak mraz', en: 'Extreme cold', de: 'Extreme Kälte', it: 'Freddo estremo' },
  'meteo.type.ice': { hr: 'Poledica', en: 'Ice', de: 'Glatteis', it: 'Ghiaccio' },
  'meteo.type.flood': { hr: 'Poplava', en: 'Flood', de: 'Hochwasser', it: 'Alluvione' },
  'meteo.type.coastal': { hr: 'Obalni valovi', en: 'Coastal waves', de: 'Küstenwellen', it: 'Onde costiere' },
  // Contextual weather advice
  'advice.rainUmbrella': { hr: 'Kiša — ponesi kišobran ☂️', en: 'Rain — bring umbrella ☂️', de: 'Regen — Schirm mitnehmen ☂️', it: 'Pioggia — porta ombrello ☂️' },
  'advice.stormStayIn': { hr: 'Oluja — izbjegavaj otvoreno ⛈️', en: 'Storm — stay indoors ⛈️', de: 'Sturm — drinnen bleiben ⛈️', it: 'Temporale — resta al chiuso ⛈️' },
  'advice.hotSunscreen': { hr: 'Vrućina — krema i voda 🧴', en: 'Hot — sunscreen & water 🧴', de: 'Heiß — Sonnencreme & Wasser 🧴', it: 'Caldo — crema solare e acqua 🧴' },
  'advice.warmNoJacket': { hr: 'Toplo jutro — bez jakne 😎', en: 'Warm morning — no jacket 😎', de: 'Warmer Morgen — keine Jacke 😎', it: 'Mattina calda — niente giacca 😎' },
  'advice.coldJacket': { hr: 'Hladno — uzmi jaknu 🧥', en: 'Cold — bring a jacket 🧥', de: 'Kalt — Jacke mitnehmen 🧥', it: 'Freddo — porta una giacca 🧥' },
  'advice.fogCareful': { hr: 'Magla — oprez u vožnji 🌫️', en: 'Fog — careful driving 🌫️', de: 'Nebel — vorsichtig fahren 🌫️', it: 'Nebbia — guida con cautela 🌫️' },
  'advice.buraWind': { hr: 'Bura puše — pazi na mostove 💨', en: 'Bura wind — watch bridges 💨', de: 'Bura — Brücken beachten 💨', it: 'Bora — attenzione ai ponti 💨' },
  'advice.niceDay': { hr: 'Lijepo vrijeme — uživaj vani ☀️', en: 'Nice day — enjoy outside ☀️', de: 'Schönes Wetter — draußen genießen ☀️', it: 'Bel tempo — goditi all\'aperto ☀️' },
  'advice.coldMorning': { hr: 'Ujutro bura — hladno 🌬️', en: 'Morning bura — cold 🌬️', de: 'Morgens Bura — kalt 🌬️', it: 'Mattina bora — freddo 🌬️' },
  // Time-slot card labels
  'now.firstFerry': { hr: 'Prvi trajekt', en: 'First ferry', de: 'Erste Fähre', it: 'Primo traghetto' },
  'now.lastFerry': { hr: 'Zadnji trajekt', en: 'Last ferry', de: 'Letzte Fähre', it: 'Ultimo traghetto' },
  'now.open247': { hr: 'Otvoreno 0-24', en: 'Open 24h', de: '24h geöffnet', it: 'Aperto 24h' },
  'now.weatherAdvice': { hr: 'Savjet za danas', en: 'Today\'s advice', de: 'Tageshinweis', it: 'Consiglio di oggi' },
  'now.taxi': { hr: 'Taxi', en: 'Taxi', de: 'Taxi', it: 'Taxi' },
  'now.taxiAvailable': { hr: 'Taxi Zadar — Google pretraga', en: 'Taxi Zadar — Google search', de: 'Taxi Zadar — Google-Suche', it: 'Taxi Zadar — Ricerca Google' },
  'now.taxiGoogleSearch': { hr: 'Taxi Zadar — Google pretraga', en: 'Taxi Zadar — Google search', de: 'Taxi Zadar — Google-Suche', it: 'Taxi Zadar — Ricerca Google' },
  'now.oldTown': { hr: 'Stari grad', en: 'Old Town', de: 'Altstadt', it: 'Centro storico' },
  'now.oldTownQuiet': { hr: 'Mirno — dobro za šetnju', en: 'Quiet — good for a walk', de: 'Ruhig — gut für Spaziergang', it: 'Tranquillo — bello per passeggiare' },
  'now.oldTownBusy': { hr: 'Gužva — očekuj čekanje', en: 'Busy — expect crowds', de: 'Voll — Wartezeiten', it: 'Affollato — aspettati coda' },
  'now.openFood': { hr: 'Otvorena hrana', en: 'Open food', de: 'Essen offen', it: 'Cibo aperto' },
  'now.bakery24': { hr: 'Pekara Ražnjević — 0-24', en: 'Bakery Ražnjević — 24h', de: 'Bäckerei Ražnjević — 24h', it: 'Panificio Ražnjević — 24h' },
  'now.gasStation': { hr: 'Benzinska — INA Put Murvice', en: 'Gas station — INA Put Murvice', de: 'Tankstelle — INA Put Murvice', it: 'Distributore — INA Put Murvice' },
  'now.morningAdvice': { hr: 'Jutarnji savjet', en: 'Morning advice', de: 'Morgenhinweis', it: 'Consiglio mattutino' },
  'now.pharmacyNoData': { hr: 'Podatak nije unesen — nazovi 112', en: 'No data — call 112', de: 'Keine Daten — 112 anrufen', it: 'Nessun dato — chiama 112' },
  // Today semantic cards
  'today.feelLabel': { hr: 'Osjećaj', en: 'Feels like', de: 'Gefühlt', it: 'Percepito' },
  'today.weatherLabel': { hr: 'Vrijeme', en: 'Weather', de: 'Wetter', it: 'Meteo' },
  'today.clothingLabel': { hr: 'Odjeća', en: 'Clothing', de: 'Kleidung', it: 'Abbigliamento' },
  'today.crowdLabel': { hr: 'Gužva', en: 'Crowd', de: 'Andrang', it: 'Folla' },
  'today.parkingLabel': { hr: 'Parking', en: 'Parking', de: 'Parken', it: 'Parcheggio' },
  'today.seaLabel': { hr: 'More', en: 'Sea', de: 'Meer', it: 'Mare' },
  // Feel
  'today.feel.veryCold': { hr: 'Vrlo hladno', en: 'Very cold', de: 'Sehr kalt', it: 'Molto freddo' },
  'today.feel.veryColdWindy': { hr: 'Ledeno i vjetrovito', en: 'Freezing & windy', de: 'Eisig & windig', it: 'Gelido e ventoso' },
  'today.feel.veryColdHumid': { hr: 'Vrlo hladno', en: 'Very cold', de: 'Sehr kalt', it: 'Molto freddo' },
  'today.feel.veryColdNight': { hr: 'Ledena noć', en: 'Freezing night', de: 'Eisige Nacht', it: 'Notte gelida' },
  'today.feel.cold': { hr: 'Hladno', en: 'Cold', de: 'Kalt', it: 'Freddo' },
  'today.feel.coldWindy': { hr: 'Hladno i vjetrovito', en: 'Cold & windy', de: 'Kalt & windig', it: 'Freddo e ventoso' },
  'today.feel.coldHumid': { hr: 'Hladno', en: 'Cold', de: 'Kalt', it: 'Freddo' },
  'today.feel.coldNight': { hr: 'Hladna noć', en: 'Cold night', de: 'Kalte Nacht', it: 'Notte fredda' },
  'today.feel.pleasant': { hr: 'Ugodno', en: 'Pleasant', de: 'Angenehm', it: 'Piacevole' },
  'today.feel.pleasantWindy': { hr: 'Svježe i vjetrovito', en: 'Fresh & breezy', de: 'Frisch & windig', it: 'Fresco e ventoso' },
  'today.feel.pleasantHumid': { hr: 'Ugodno', en: 'Pleasant', de: 'Angenehm', it: 'Piacevole' },
  'today.feel.pleasantNight': { hr: 'Ugodna večer', en: 'Pleasant evening', de: 'Angenehmer Abend', it: 'Serata piacevole' },
  'today.feel.warm': { hr: 'Toplo', en: 'Warm', de: 'Warm', it: 'Caldo' },
  'today.feel.warmWindy': { hr: 'Toplo s vjetrom', en: 'Warm & breezy', de: 'Warm & windig', it: 'Caldo e ventoso' },
  'today.feel.warmHumid': { hr: 'Toplo i sparno', en: 'Warm & muggy', de: 'Warm & schwül', it: 'Caldo e afoso' },
  'today.feel.warmNight': { hr: 'Topla noć', en: 'Warm night', de: 'Warme Nacht', it: 'Notte calda' },
  'today.feel.hot': { hr: 'Vruće', en: 'Hot', de: 'Heiß', it: 'Molto caldo' },
  'today.feel.hotWindy': { hr: 'Vruće s vjetrom', en: 'Hot & windy', de: 'Heiß & windig', it: 'Caldo e ventoso' },
  'today.feel.hotHumid': { hr: 'Vruće i sparno', en: 'Hot & humid', de: 'Heiß & schwül', it: 'Caldo e afoso' },
  'today.feel.hotNight': { hr: 'Vruća noć', en: 'Hot night', de: 'Heiße Nacht', it: 'Notte calda' },
  // Weather advice
  'today.weather.idealOutside': { hr: 'Idealno za van', en: 'Ideal for outside', de: 'Ideal für draußen', it: 'Ideale per uscire' },
  'today.weather.neutral': { hr: 'Neutralno', en: 'Neutral', de: 'Neutral', it: 'Neutro' },
  'today.weather.bringUmbrella': { hr: 'Ponesi kišobran', en: 'Bring umbrella', de: 'Schirm mitnehmen', it: 'Porta ombrello' },
  'today.weather.stayInside': { hr: 'Bolje unutra', en: 'Better stay in', de: 'Besser drinnen', it: 'Meglio dentro' },
  'today.weather.foggy': { hr: 'Magla — oprez', en: 'Fog — careful', de: 'Nebel — Vorsicht', it: 'Nebbia — attenzione' },
  // Clothing
  'today.clothing.jacket': { hr: 'Jakna 🧥', en: 'Jacket 🧥', de: 'Jacke 🧥', it: 'Giacca 🧥' },
  'today.clothing.longClothes': { hr: 'Dugo 👖', en: 'Long clothes 👖', de: 'Lange Kleidung 👖', it: 'Vestiti lunghi 👖' },
  'today.clothing.lightClothes': { hr: 'Lagano 👕', en: 'Light clothes 👕', de: 'Leichte Kleidung 👕', it: 'Vestiti leggeri 👕' },
  'today.clothing.shorts': { hr: 'Kratko 🩳', en: 'Shorts 🩳', de: 'Kurz 🩳', it: 'Corti 🩳' },
  // Crowd
  'today.crowd.empty': { hr: 'Prazno', en: 'Empty', de: 'Leer', it: 'Vuoto' },
  'today.crowd.fewPeople': { hr: 'Malo ljudi', en: 'Few people', de: 'Wenige Leute', it: 'Poche persone' },
  'today.crowd.moderate': { hr: 'Umjereno', en: 'Moderate', de: 'Mäßig', it: 'Moderato' },
  'today.crowd.crowded': { hr: 'Gužva', en: 'Crowded', de: 'Voll', it: 'Affollato' },
  'today.crowd.packed': { hr: 'Prepuno', en: 'Packed', de: 'Überfüllt', it: 'Strapieno' },
  // Parking semantic
  'today.parking.free': { hr: 'Besplatno', en: 'Free', de: 'Kostenlos', it: 'Gratuito' },
  'today.parking.available': { hr: 'Ima mjesta', en: 'Available', de: 'Verfügbar', it: 'Disponibile' },
  'today.parking.hardToFind': { hr: 'Teško naći', en: 'Hard to find', de: 'Schwer zu finden', it: 'Difficile trovare' },
  'today.parking.almostImpossible': { hr: 'Gotovo nemoguće', en: 'Nearly impossible', de: 'Fast unmöglich', it: 'Quasi impossibile' },
  // Sea
  'today.sea.cold': { hr: 'Hladno', en: 'Cold', de: 'Kalt', it: 'Freddo' },
  'today.sea.fresh': { hr: 'Svježe', en: 'Fresh', de: 'Frisch', it: 'Fresco' },
  'today.sea.pleasant': { hr: 'Ugodno', en: 'Pleasant', de: 'Angenehm', it: 'Piacevole' },
  'today.sea.warm': { hr: 'Toplo', en: 'Warm', de: 'Warm', it: 'Caldo' },
  // Situational modes
  'mode.morning': { hr: 'Jutarnji mod', en: 'Morning mode', de: 'Morgenmodus', it: 'Modalità mattina' },
  'mode.day': { hr: 'Dnevni mod', en: 'Day mode', de: 'Tagesmodus', it: 'Modalità giorno' },
  'mode.evening': { hr: 'Večernji mod', en: 'Evening mode', de: 'Abendmodus', it: 'Modalità sera' },
  'mode.night': { hr: 'Noćni mod', en: 'Night mode', de: 'Nachtmodus', it: 'Modalità notte' },
  'mode.bad_weather': { hr: 'Loše vrijeme', en: 'Bad weather', de: 'Schlechtwetter', it: 'Maltempo' },
  'mode.badWeatherAlert': { hr: 'Upozorenje aktivno', en: 'Alert active', de: 'Warnung aktiv', it: 'Allerta attiva' },
  // Mode-specific card labels
  'mode.morningCafe': { hr: 'Kafić / Pekara', en: 'Cafe / Bakery', de: 'Café / Bäckerei', it: 'Caffè / Panificio' },
  'mode.morningCafeAnswer': { hr: 'Otvoreni kafići u blizini ☕', en: 'Open cafes nearby ☕', de: 'Offene Cafés in der Nähe ☕', it: 'Caffè aperti vicino ☕' },
  'mode.shopsOpen': { hr: 'Trgovine sada', en: 'Shops open', de: 'Geschäfte offen', it: 'Negozi aperti' },
  'mode.shopsOpenAnswer': { hr: 'Otvorene trgovine u blizini 🛍️', en: 'Open shops nearby 🛍️', de: 'Offene Geschäfte in der Nähe 🛍️', it: 'Negozi aperti vicino 🛍️' },
  'mode.institutions': { hr: 'Javne službe', en: 'Public services', de: 'Öffentliche Dienste', it: 'Servizi pubblici' },
  'mode.institutionsAnswer': { hr: 'Pošta, banka, institucije 🏛️', en: 'Post, bank, services 🏛️', de: 'Post, Bank, Behörden 🏛️', it: 'Posta, banca, servizi 🏛️' },
  'mode.restaurants': { hr: 'Restorani večeras', en: 'Restaurants tonight', de: 'Restaurants heute Abend', it: 'Ristoranti stasera' },
  'mode.restaurantsAnswer': { hr: 'Otvoreni restorani u blizini 🍽️', en: 'Open restaurants nearby 🍽️', de: 'Offene Restaurants in der Nähe 🍽️', it: 'Ristoranti aperti vicino 🍽️' },
  'mode.cinemaTonight': { hr: 'Kino večeras', en: 'Cinema tonight', de: 'Kino heute Abend', it: 'Cinema stasera' },
  'mode.cinemaTonightAnswer': { hr: 'Projekcije večeras 🎬', en: 'Screenings tonight 🎬', de: 'Vorführungen heute Abend 🎬', it: 'Proiezioni stasera 🎬' },
  'mode.indoorActivity': { hr: 'Zatvorene aktivnosti', en: 'Indoor activities', de: 'Indoor-Aktivitäten', it: 'Attività al chiuso' },
  'mode.indoorActivityAnswer': { hr: 'Kino, muzej, shopping 🏠', en: 'Cinema, museum, shopping 🏠', de: 'Kino, Museum, Shopping 🏠', it: 'Cinema, museo, shopping 🏠' },
  // Correction popup
  'correction.isCorrect': { hr: 'Je li ovaj podatak točan?', en: 'Is this data correct?', de: 'Sind diese Daten korrekt?', it: 'Questo dato è corretto?' },
  'correction.correct': { hr: 'Točno', en: 'Correct', de: 'Korrekt', it: 'Corretto' },
  'correction.suggest': { hr: 'Predloži ispravak', en: 'Suggest correction', de: 'Korrektur vorschlagen', it: 'Suggerisci correzione' },
  'correction.notExists': { hr: 'Ne postoji više', en: 'No longer exists', de: 'Existiert nicht mehr', it: 'Non esiste più' },
  'correction.suggestNew': { hr: 'Unesite ispravnu vrijednost:', en: 'Enter the correct value:', de: 'Geben Sie den korrekten Wert ein:', it: 'Inserisci il valore corretto:' },
  'correction.submit': { hr: 'Pošalji', en: 'Submit', de: 'Absenden', it: 'Invia' },
  // City Pulse
  'pulse.title': { hr: 'Gdje je živo?', en: 'Where\'s it lively?', de: 'Wo ist was los?', it: 'Dove c\'è vita?' },
  'pulse.subtitle': { hr: 'Procjena aktivnosti u gradu u stvarnom vremenu', en: 'Real-time city activity estimate', de: 'Echtzeit-Schätzung der Stadtaktivität', it: 'Stima in tempo reale dell\'attività cittadina' },
  'pulse.privacy': { hr: 'Ova procjena temelji se na vremenu, dobu dana, događanjima i anonimnim agregiranim signalima. Aplikacija ne prati lokaciju korisnika.', en: 'This estimate is based on weather, time of day, events and anonymous aggregated signals. The app does not track user location.', de: 'Diese Schätzung basiert auf Wetter, Tageszeit, Veranstaltungen und anonymen aggregierten Signalen. Die App verfolgt den Standort der Benutzer nicht.', it: 'Questa stima si basa su meteo, ora del giorno, eventi e segnali aggregati anonimi. L\'app non traccia la posizione degli utenti.' },
  'pulse.zone.poluotok': { hr: 'Poluotok', en: 'Peninsula', de: 'Halbinsel', it: 'Penisola' },
  'pulse.zone.riva': { hr: 'Riva / Forum', en: 'Riva / Forum', de: 'Riva / Forum', it: 'Riva / Foro' },
  'pulse.zone.borik': { hr: 'Borik', en: 'Borik', de: 'Borik', it: 'Borik' },
  'pulse.zone.visnjik': { hr: 'Višnjik', en: 'Višnjik', de: 'Višnjik', it: 'Višnjik' },
  'pulse.zone.gazenica': { hr: 'Gaženica', en: 'Gaženica', de: 'Gaženica', it: 'Gaženica' },
  'pulse.level.quiet': { hr: 'Mirno', en: 'Quiet', de: 'Ruhig', it: 'Tranquillo' },
  'pulse.level.light': { hr: 'Lagano', en: 'Light', de: 'Leicht', it: 'Leggero' },
  'pulse.level.pleasant': { hr: 'Ugodno', en: 'Pleasant', de: 'Angenehm', it: 'Piacevole' },
  'pulse.level.lively': { hr: 'Živo', en: 'Lively', de: 'Lebhaft', it: 'Vivace' },
  'pulse.level.peak': { hr: 'Vrhunac', en: 'Peak', de: 'Höhepunkt', it: 'Picco' },
  'pulse.desc.quietMorning': { hr: 'Tiho jutro', en: 'Quiet morning', de: 'Ruhiger Morgen', it: 'Mattina tranquilla' },
  'pulse.desc.quietDay': { hr: 'Miran dan', en: 'Calm day', de: 'Ruhiger Tag', it: 'Giorno calmo' },
  'pulse.desc.quietEvening': { hr: 'Tiha večer', en: 'Quiet evening', de: 'Ruhiger Abend', it: 'Sera tranquilla' },
  'pulse.desc.quietNight': { hr: 'Mirna noć', en: 'Peaceful night', de: 'Friedliche Nacht', it: 'Notte serena' },
  'pulse.desc.lightMorning': { hr: 'Jutarnja kava', en: 'Morning coffee', de: 'Morgenkaffee', it: 'Caffè mattutino' },
  'pulse.desc.lightDay': { hr: 'Lagana aktivnost', en: 'Light activity', de: 'Leichte Aktivität', it: 'Attività leggera' },
  'pulse.desc.lightEvening': { hr: 'Lagano popodne', en: 'Easy evening', de: 'Leichter Abend', it: 'Sera leggera' },
  'pulse.desc.lightNight': { hr: 'Malo ljudi', en: 'Few around', de: 'Wenig los', it: 'Poca gente' },
  'pulse.desc.pleasantMorning': { hr: 'Ugodno jutro', en: 'Pleasant morning', de: 'Angenehmer Morgen', it: 'Mattina piacevole' },
  'pulse.desc.pleasantDay': { hr: 'Idealno za šetnju', en: 'Perfect for a walk', de: 'Ideal für einen Spaziergang', it: 'Ideale per passeggiata' },
  'pulse.desc.pleasantEvening': { hr: 'Ugodna večer', en: 'Pleasant evening', de: 'Angenehmer Abend', it: 'Sera piacevole' },
  'pulse.desc.pleasantNight': { hr: 'Ugodna noć', en: 'Pleasant night', de: 'Angenehme Nacht', it: 'Notte piacevole' },
  'pulse.desc.livelyMorning': { hr: 'Živahno jutro', en: 'Busy morning', de: 'Lebhafter Morgen', it: 'Mattina vivace' },
  'pulse.desc.livelyDay': { hr: 'Pun dan', en: 'Full day', de: 'Voller Tag', it: 'Giorno pieno' },
  'pulse.desc.livelyEvening': { hr: 'Navečer popularno', en: 'Popular evenings', de: 'Beliebte Abende', it: 'Serate popolari' },
  'pulse.desc.livelyNight': { hr: 'Večernja gužva', en: 'Evening buzz', de: 'Abendtrubel', it: 'Fermento serale' },
  'pulse.desc.peakMorning': { hr: 'Jutarnji vrh', en: 'Morning peak', de: 'Morgenspitze', it: 'Picco mattutino' },
  'pulse.desc.peakDay': { hr: 'Dnevni vrhunac', en: 'Daytime peak', de: 'Tagesspitze', it: 'Picco diurno' },
  'pulse.desc.peakEvening': { hr: 'Večernji vrhunac', en: 'Evening peak', de: 'Abendspitze', it: 'Picco serale' },
  'pulse.desc.peakNight': { hr: 'Noćni život', en: 'Nightlife', de: 'Nachtleben', it: 'Vita notturna' },
  'pulse.walk': { hr: 'Šetnja', en: 'Walk', de: 'Spaziergang', it: 'Passeggiata' },
  'pulse.voteQuestion': { hr: 'Kako je ovdje?', en: 'How is it here?', de: 'Wie ist es hier?', it: 'Com\'è qui?' },
  'pulse.vote.quiet': { hr: 'Mirno', en: 'Quiet', de: 'Ruhig', it: 'Tranquillo' },
  'pulse.vote.moderate': { hr: 'Umjereno', en: 'Moderate', de: 'Mäßig', it: 'Moderato' },
  'pulse.vote.lively': { hr: 'Živo', en: 'Lively', de: 'Lebhaft', it: 'Vivace' },
  'pulse.voteThanks': { hr: 'Hvala na doprinosu!', en: 'Thanks for contributing!', de: 'Danke für Ihren Beitrag!', it: 'Grazie per il contributo!' },
  'pulse.voteError': { hr: 'Greška pri slanju', en: 'Error submitting', de: 'Fehler beim Senden', it: 'Errore nell\'invio' },
  'pulse.voteSubmitted': { hr: 'Vaš glas je zabilježen ✓', en: 'Your vote is recorded ✓', de: 'Ihre Stimme wurde erfasst ✓', it: 'Il tuo voto è stato registrato ✓' },
  'pulse.rec.peakTonight': { hr: '🔥 Preporučeno večeras — grad je živ!', en: '🔥 Recommended tonight — city is alive!', de: '🔥 Heute Abend empfohlen — die Stadt lebt!', it: '🔥 Consigliato stasera — la città è viva!' },
  'pulse.rec.quietWalk': { hr: '🌿 Dobar trenutak za šetnju gradom', en: '🌿 Good time for a city walk', de: '🌿 Gute Zeit für einen Stadtspaziergang', it: '🌿 Buon momento per una passeggiata' },
  'pulse.rec.rainy': { hr: '☔ Kišovito — razmisli o zatvorenim aktivnostima', en: '☔ Rainy — consider indoor activities', de: '☔ Regnerisch — denken Sie an Innenaktivitäten', it: '☔ Pioggia — considera attività al chiuso' },
  // Smoking status
  'smoking.title': { hr: 'Pušenje', en: 'Smoking', de: 'Rauchen', it: 'Fumo' },
  'smoking.allowed': { hr: 'Pušenje dozvoljeno', en: 'Smoking allowed', de: 'Rauchen erlaubt', it: 'Fumo consentito' },
  'smoking.partial': { hr: 'Odvojeni dio', en: 'Separated area', de: 'Getrennter Bereich', it: 'Area separata' },
  'smoking.notAllowed': { hr: 'Nepušački', en: 'Non-smoking', de: 'Nichtraucher', it: 'Non fumatori' },
  'smoking.unconfirmed': { hr: 'Nije potvrđeno', en: 'Unconfirmed', de: 'Nicht bestätigt', it: 'Non confermato' },
  'smoking.confirmed': { hr: 'Potvrđeno', en: 'Confirmed', de: 'Bestätigt', it: 'Confermato' },
  'smoking.reportStatus': { hr: 'Prijavi status pušenja:', en: 'Report smoking status:', de: 'Raucherstatus melden:', it: 'Segnala stato fumo:' },
  'smoking.thankYou': { hr: 'Hvala! Ažurirat ćemo kad bude dovoljno potvrda.', en: 'Thanks! We\'ll update when enough confirmations arrive.', de: 'Danke! Wir aktualisieren bei genügend Bestätigungen.', it: 'Grazie! Aggiorneremo con sufficienti conferme.' },
  'smoking.cooldown': { hr: 'Već ste prijavili status za ovaj kafić. Pokušajte ponovno za 30 dana.', en: 'You already reported this cafe. Try again in 30 days.', de: 'Sie haben dieses Café bereits gemeldet. Versuchen Sie es in 30 Tagen erneut.', it: 'Hai già segnalato questo caffè. Riprova tra 30 giorni.' },
  'smoking.disclaimer': { hr: 'Informativno – temelji se na prijavama korisnika. Ako se pravila promijene, prijavite ispravak.', en: 'Informational — based on user reports. If rules change, report a correction.', de: 'Informativ — basiert auf Nutzermeldungen. Bei Regeländerungen melden Sie eine Korrektur.', it: 'Informativo — basato su segnalazioni utenti. Se le regole cambiano, segnala una correzione.' },
  // Add cafe
  'addCafe.title': { hr: 'Dodaj novi kafić', en: 'Add new cafe', de: 'Neues Café hinzufügen', it: 'Aggiungi nuovo caffè' },
  'addCafe.addButton': { hr: '➕ Dodaj kafić', en: '➕ Add cafe', de: '➕ Café hinzufügen', it: '➕ Aggiungi caffè' },
  'addCafe.name': { hr: 'Naziv', en: 'Name', de: 'Name', it: 'Nome' },
  'addCafe.namePlaceholder': { hr: 'npr. Caffe bar Sunset', en: 'e.g. Cafe Bar Sunset', de: 'z.B. Café Bar Sunset', it: 'es. Caffè Bar Sunset' },
  'addCafe.address': { hr: 'Adresa', en: 'Address', de: 'Adresse', it: 'Indirizzo' },
  'addCafe.addressPlaceholder': { hr: 'npr. Široka ulica 5, Zadar', en: 'e.g. Široka ulica 5, Zadar', de: 'z.B. Široka ulica 5, Zadar', it: 'es. Široka ulica 5, Zadar' },
  'addCafe.phone': { hr: 'Telefon', en: 'Phone', de: 'Telefon', it: 'Telefono' },
  'addCafe.website': { hr: 'Web stranica', en: 'Website', de: 'Webseite', it: 'Sito web' },
  'addCafe.optional': { hr: 'opcionalno', en: 'optional', de: 'optional', it: 'opzionale' },
  'addCafe.submit': { hr: 'Pošalji prijedlog', en: 'Submit suggestion', de: 'Vorschlag senden', it: 'Invia suggerimento' },
  'addCafe.thankYou': { hr: 'Hvala! Vaš prijedlog je zaprimljen.', en: 'Thanks! Your suggestion has been received.', de: 'Danke! Ihr Vorschlag wurde empfangen.', it: 'Grazie! Il tuo suggerimento è stato ricevuto.' },
  'addCafe.pendingReview': { hr: 'Prijedlog će biti pregledan i dodan ako bude odobren.', en: 'Your submission will be reviewed and added if approved.', de: 'Ihr Eintrag wird überprüft und bei Genehmigung hinzugefügt.', it: 'Il tuo invio sarà revisionato e aggiunto se approvato.' },
  'addCafe.limitReached': { hr: 'Dosegnuli ste dnevni limit prijedloga. Pokušajte sutra.', en: 'You reached the daily suggestion limit. Try tomorrow.', de: 'Tageslimit erreicht. Versuchen Sie es morgen.', it: 'Limite giornaliero raggiunto. Riprova domani.' },
  'addCafe.error': { hr: 'Greška pri slanju. Pokušajte ponovno.', en: 'Error submitting. Please try again.', de: 'Fehler beim Senden. Bitte versuchen Sie es erneut.', it: 'Errore nell\'invio. Riprova.' },
  'addCafe.disclaimer': { hr: 'Svi prijedlozi prolaze moderaciju. Neprimjereni unosi bit će ignorirani.', en: 'All suggestions go through moderation. Inappropriate entries will be ignored.', de: 'Alle Vorschläge werden moderiert. Unangemessene Einträge werden ignoriert.', it: 'Tutti i suggerimenti passano per moderazione. Inserimenti inappropriati saranno ignorati.' },
  // Smart badges
  'badge.meteoalarm': { hr: 'Meteoalarm', en: 'Meteoalarm', de: 'Meteoalarm', it: 'Meteoalarm' },
  'badge.buraStrong': { hr: 'Bura jaka', en: 'Strong Bura', de: 'Starke Bura', it: 'Bora forte' },
  'badge.jugoStrong': { hr: 'Jugo jako', en: 'Strong Jugo', de: 'Starker Jugo', it: 'Scirocco forte' },
  // Detail modals
  'detail.weatherTitle': { hr: 'Detalji vremena', en: 'Weather Details', de: 'Wetterdetails', it: 'Dettagli meteo' },
  'detail.temperature': { hr: 'Temperatura', en: 'Temperature', de: 'Temperatur', it: 'Temperatura' },
  'detail.humidity': { hr: 'Vlažnost', en: 'Humidity', de: 'Luftfeuchtigkeit', it: 'Umidità' },
  'detail.wind': { hr: 'Vjetar', en: 'Wind', de: 'Wind', it: 'Vento' },
  'detail.gusts': { hr: 'Udari', en: 'Gusts', de: 'Böen', it: 'Raffiche' },
  'detail.direction': { hr: 'Smjer', en: 'Direction', de: 'Richtung', it: 'Direzione' },
  'detail.sunrise': { hr: 'Izlazak sunca', en: 'Sunrise', de: 'Sonnenaufgang', it: 'Alba' },
  'detail.sunset': { hr: 'Zalazak sunca', en: 'Sunset', de: 'Sonnenuntergang', it: 'Tramonto' },
  'detail.openForecast': { hr: 'Detaljna prognoza (DHMZ)', en: 'Detailed forecast (DHMZ)', de: 'Detaillierte Prognose (DHMZ)', it: 'Previsioni dettagliate (DHMZ)' },
  'detail.crowdTitle': { hr: 'Gužva u starom gradu', en: 'Old Town Crowd', de: 'Andrang in der Altstadt', it: 'Folla nel centro storico' },
  'detail.currentLevel': { hr: 'Trenutna procjena', en: 'Current estimate', de: 'Aktuelle Schätzung', it: 'Stima attuale' },
  'detail.timeNow': { hr: 'Sat', en: 'Hour', de: 'Uhrzeit', it: 'Ora' },
  'detail.weekend': { hr: 'Vikend', en: 'Weekend', de: 'Wochenende', it: 'Fine settimana' },
  'detail.summer': { hr: 'Sezona', en: 'Season', de: 'Saison', it: 'Stagione' },
  'detail.crowdExplain': { hr: 'Procjena se temelji na dobu dana, danu u tjednu i sezoni. Nije mjerenje u stvarnom vremenu.', en: 'Estimate based on time of day, day of week, and season. Not a real-time measurement.', de: 'Schätzung basierend auf Tageszeit, Wochentag und Saison. Keine Echtzeitmessung.', it: 'Stima basata su ora del giorno, giorno della settimana e stagione. Non una misurazione in tempo reale.' },
  'detail.seaTitle': { hr: 'Temperatura mora', en: 'Sea Temperature', de: 'Meerestemperatur', it: 'Temperatura del mare' },
  'detail.seaTemp': { hr: 'Temperatura', en: 'Temperature', de: 'Temperatur', it: 'Temperatura' },
  'detail.seaFeeling': { hr: 'Osjećaj', en: 'Feeling', de: 'Gefühl', it: 'Sensazione' },
  'detail.seaColdAdvice': { hr: 'More je prehladno za kupanje. Preporučamo šetnju obalom.', en: 'Sea is too cold for swimming. We recommend a coastal walk.', de: 'Meer zu kalt zum Schwimmen. Küstenspaziergang empfohlen.', it: 'Mare troppo freddo per nuotare. Consigliamo una passeggiata costiera.' },
  'detail.seaFreshAdvice': { hr: 'More je svježe ali ugodno za odvažnije kupače.', en: 'Sea is fresh but pleasant for brave swimmers.', de: 'Meer ist frisch, aber angenehm für Mutige.', it: 'Mare fresco ma piacevole per i nuotatori coraggiosi.' },
  'detail.seaWarmAdvice': { hr: 'More je ugodno za kupanje! Uživajte.', en: 'Sea is pleasant for swimming! Enjoy.', de: 'Meer angenehm zum Schwimmen! Genießen Sie es.', it: 'Mare piacevole per nuotare! Godetevi.' },
  'detail.meteoAlertTitle': { hr: 'Meteo upozorenja', en: 'Weather Alerts', de: 'Wetterwarnungen', it: 'Allerte meteo' },
  'detail.windTitle': { hr: 'Vjetar — detalji', en: 'Wind — Details', de: 'Wind — Details', it: 'Vento — Dettagli' },
  'detail.windType': { hr: 'Tip vjetra', en: 'Wind type', de: 'Windart', it: 'Tipo di vento' },
  'detail.windAdvice': { hr: 'Jak vjetar može utjecati na trajektne linije i cestovni promet, posebno na mostovima. Provjerite HAK za stanje na cestama.', en: 'Strong wind may affect ferry lines and road traffic, especially on bridges. Check HAK for road conditions.', de: 'Starker Wind kann Fährlinien und Straßenverkehr beeinträchtigen, besonders auf Brücken. Prüfen Sie HAK für Straßenverhältnisse.', it: 'Il vento forte può influenzare le linee traghetto e il traffico stradale, specialmente sui ponti. Controlla HAK per le condizioni stradali.' },
  // Outdoor recommendation
  'outdoor.label.good': { hr: 'Dobar trenutak za šetnju', en: 'Good time for a walk', de: 'Gute Zeit für einen Spaziergang', it: 'Buon momento per passeggiare' },
  'outdoor.label.ok': { hr: 'Kratka šetnja – jakna', en: 'Short walk – bring jacket', de: 'Kurzer Spaziergang – Jacke', it: 'Breve passeggiata – giacca' },
  'outdoor.label.bad': { hr: 'Ponesi kišobran / kratko i blizu', en: 'Bring umbrella / stay close', de: 'Schirm mitnehmen / in der Nähe', it: 'Porta ombrello / resta vicino' },
  'outdoor.label.danger': { hr: 'Ne preporučuje se van', en: 'Not recommended to go out', de: 'Nicht empfohlen rauszugehen', it: 'Sconsigliato uscire' },
  'outdoor.label.noData': { hr: 'Provjeri uvjete', en: 'Check conditions', de: 'Bedingungen prüfen', it: 'Controlla le condizioni' },
  'outdoor.reason.stable': { hr: 'Stabilno — bez oborine, slab vjetar', en: 'Stable — no rain, light wind', de: 'Stabil — kein Regen, leichter Wind', it: 'Stabile — senza pioggia, vento leggero' },
  'outdoor.reason.coolJacket': { hr: 'Hladno ali bez oborine — uzmi jaknu', en: 'Cool but dry — bring a jacket', de: 'Kühl aber trocken — Jacke mitnehmen', it: 'Fresco ma asciutto — porta giacca' },
  'outdoor.reason.maybeRain': { hr: 'Moguća kiša — prati prognozu', en: 'Rain possible — watch forecast', de: 'Regen möglich — Prognose beachten', it: 'Pioggia possibile — segui previsioni' },
  'outdoor.reason.rain': { hr: 'Kiša u tijeku', en: 'Rain ongoing', de: 'Regen aktiv', it: 'Pioggia in corso' },
  'outdoor.reason.lightRain': { hr: 'Lagana kiša — kratko i blizu', en: 'Light rain — keep it short', de: 'Leichter Regen — kurz halten', it: 'Pioggia leggera — breve e vicino' },
  'outdoor.reason.rainLikely': { hr: 'Velika šansa za kišu', en: 'High chance of rain', de: 'Hohe Regenwahrscheinlichkeit', it: 'Alta probabilità di pioggia' },
  'outdoor.reason.strongWind': { hr: 'Jaki udari vjetra', en: 'Strong wind gusts', de: 'Starke Windböen', it: 'Forti raffiche di vento' },
  'outdoor.reason.windy': { hr: 'Vjetrovito', en: 'Windy', de: 'Windig', it: 'Ventoso' },
  'outdoor.reason.storm': { hr: 'Pljuskovi ili oluja', en: 'Heavy showers or storm', de: 'Starke Schauer oder Sturm', it: 'Forti acquazzoni o temporale' },
  'outdoor.reason.veryCold': { hr: 'Jako hladno — ispod 3°C', en: 'Very cold — below 3°C', de: 'Sehr kalt — unter 3°C', it: 'Molto freddo — sotto 3°C' },
  'outdoor.reason.meteoAlert': { hr: 'Upozorenje aktivno — oprez', en: 'Alert active — caution', de: 'Warnung aktiv — Vorsicht', it: 'Allerta attiva — cautela' },
  'outdoor.reason.meteoYellow': { hr: 'Upozorenje (žuto) — prati situaciju', en: 'Alert (yellow) — monitor conditions', de: 'Warnung (gelb) — Lage beobachten', it: 'Allerta (gialla) — monitora condizioni' },
  'outdoor.reason.neutral': { hr: 'Umjereni uvjeti', en: 'Moderate conditions', de: 'Mäßige Bedingungen', it: 'Condizioni moderate' },
  'outdoor.reason.noData': { hr: 'Podaci se osvježavaju', en: 'Data refreshing', de: 'Daten werden aktualisiert', it: 'Aggiornamento dati' },
  'outdoor.updated': { hr: 'Ažurirano:', en: 'Updated:', de: 'Aktualisiert:', it: 'Aggiornato:' },
  // What is happening today
  'happening.sectionTitle': { hr: 'Što se događa danas', en: 'What\'s happening today', de: 'Was passiert heute', it: 'Cosa succede oggi' },
  'happening.live': { hr: 'UŽIVO', en: 'LIVE', de: 'LIVE', it: 'DAL VIVO' },
  'happening.liveBadge': { hr: 'UŽIVO', en: 'LIVE', de: 'LIVE', it: 'LIVE' },
  'happening.tonight': { hr: 'Večeras igra', en: 'Playing tonight', de: 'Spielt heute Abend', it: 'Stasera gioca' },
  'happening.soonBadge': { hr: 'USKORO', en: 'SOON', de: 'BALD', it: 'PRESTO' },
  'happening.expectCrowds': { hr: 'Očekuj gužvu u kafićima', en: 'Expect crowds in cafes', de: 'Erwarte Gedränge in Cafés', it: 'Aspettati folla nei bar' },
  'happening.finishedBadge': { hr: 'ZAVRŠENO', en: 'FINISHED', de: 'BEENDET', it: 'FINITO' },
  'happening.matchEnded': { hr: 'Utakmica završila', en: 'Match ended', de: 'Spiel beendet', it: 'Partita finita' },
  'happening.cityAlive': { hr: 'Grad živ večeras', en: 'City alive tonight', de: 'Stadt lebt heute Abend', it: 'Città viva stasera' },
  'happening.today': { hr: 'Danas', en: 'Today', de: 'Heute', it: 'Oggi' },
  'happening.calmDay': { hr: 'Miran dan u gradu', en: 'Calm day in the city', de: 'Ruhiger Tag in der Stadt', it: 'Giornata tranquilla in città' },
  'happening.calmAfternoon': { hr: 'Mirno popodne u gradu', en: 'Quiet afternoon in the city', de: 'Ruhiger Nachmittag in der Stadt', it: 'Pomeriggio tranquillo in città' },
  'happening.calmEvening': { hr: 'Mirna večer u gradu', en: 'Quiet evening in the city', de: 'Ruhiger Abend in der Stadt', it: 'Serata tranquilla in città' },
  'happening.livelyWeekend': { hr: 'Živ vikend u centru', en: 'Lively weekend downtown', de: 'Lebhaftes Wochenende in der Innenstadt', it: 'Weekend vivace in centro' },
  'happening.nothingMajor': { hr: 'Nema važnijih događanja', en: 'No major events', de: 'Keine größeren Ereignisse', it: 'Nessun evento importante' },
  'happening.crowdExpected': { hr: 'Očekuj promet', en: 'Expect traffic', de: 'Verkehr erwartet', it: 'Aspettati traffico' },
  'happening.at': { hr: 'u', en: 'at', de: 'um', it: 'alle' },
  'happening.liveMatch': { hr: 'Utakmica u tijeku', en: 'Match in progress', de: 'Spiel läuft', it: 'Partita in corso' },
  'happening.todayPlays': { hr: 'Danas igra Zadar', en: 'Zadar plays today', de: 'Zadar spielt heute', it: 'Zadar gioca oggi' },
  'happening.todayPlaysHajduk': { hr: 'Danas igra Hajduk', en: 'Hajduk plays today', de: 'Hajduk spielt heute', it: 'Hajduk gioca oggi' },
  'happening.todayPlaysCroatia': { hr: 'Danas igra Hrvatska', en: 'Croatia plays today', de: 'Kroatien spielt heute', it: 'La Croazia gioca oggi' },
  'happening.todayMatchGeneric': { hr: 'Utakmica danas', en: 'Match today', de: 'Spiel heute', it: 'Partita oggi' },
  'happening.tomorrowPlays': { hr: 'Sutra igra Zadar', en: 'Zadar plays tomorrow', de: 'Zadar spielt morgen', it: 'Zadar gioca domani' },
  'happening.tomorrowPlaysHajduk': { hr: 'Sutra igra Hajduk', en: 'Hajduk plays tomorrow', de: 'Hajduk spielt morgen', it: 'Hajduk gioca domani' },
  'happening.tomorrowPlaysCroatia': { hr: 'Sutra igra Hrvatska', en: 'Croatia plays tomorrow', de: 'Kroatien spielt morgen', it: 'La Croazia gioca domani' },
  'happening.tomorrowMatchGeneric': { hr: 'Utakmica sutra', en: 'Match tomorrow', de: 'Spiel morgen', it: 'Partita domani' },
  'happening.nextMatch': { hr: 'Sljedeća utakmica', en: 'Next match', de: 'Nächstes Spiel', it: 'Prossima partita' },
  'happening.lastResult': { hr: 'Zadnji rezultat', en: 'Last result', de: 'Letztes Ergebnis', it: 'Ultimo risultato' },
  'happening.noSportsData': { hr: 'Nema dostupnih sportskih podataka', en: 'No sports data available', de: 'Keine Sportdaten verfügbar', it: 'Nessun dato sportivo disponibile' },
  'happening.apiUnavailable': { hr: 'Privremeni problem s izvorom rezultata. Prikazujemo zadnje poznate informacije.', en: 'Temporary issue with results source. Showing last known data.', de: 'Vorübergehendes Problem mit der Ergebnisquelle. Letzte bekannte Daten werden angezeigt.', it: 'Problema temporaneo con la fonte dei risultati. Mostriamo gli ultimi dati noti.' },
  'happening.noUpcoming': { hr: 'Trenutno nema utakmica u sljedećih 30 dana za praćene timove.', en: 'No matches in the next 30 days for tracked teams.', de: 'Keine Spiele in den nächsten 30 Tagen für verfolgte Teams.', it: 'Nessuna partita nei prossimi 30 giorni per le squadre seguite.' },
  'happening.autoUpdateDown': { hr: 'Automatsko ažuriranje privremeno nedostupno', en: 'Auto-update temporarily unavailable', de: 'Auto-Update vorübergehend nicht verfügbar', it: 'Aggiornamento automatico temporaneamente non disponibile' },
  'happening.sports': { hr: 'Sport', en: 'Sports', de: 'Sport', it: 'Sport' },
  'happening.f1': { hr: 'Formula 1', en: 'Formula 1', de: 'Formel 1', it: 'Formula 1' },
  'happening.championsLeague': { hr: 'Liga prvaka', en: 'Champions League', de: 'Champions League', it: 'Champions League' },
  'happening.croatiaNT': { hr: 'Hrvatska reprezentacija', en: 'Croatia NT', de: 'Kroatien', it: 'Croazia' },
  'happening.communitySubmitted': { hr: 'Doprinos zajednice', en: 'Community submitted', de: 'Von Gemeinschaft eingereicht', it: 'Contributo della comunità' },
  'happening.awaitingApproval': { hr: 'Čeka odobrenje', en: 'Awaiting approval', de: 'Wartet auf Genehmigung', it: 'In attesa di approvazione' },
  'happening.updated': { hr: 'Ažurirano', en: 'Updated', de: 'Aktualisiert', it: 'Aggiornato' },
  'happening.nextRace': { hr: 'Sljedeća utrka', en: 'Next race', de: 'Nächstes Rennen', it: 'Prossima gara' },
  'happening.lastRace': { hr: 'Zadnja utrka', en: 'Last race', de: 'Letztes Rennen', it: 'Ultima gara' },
  'happening.submitMatch': { hr: 'Predloži utakmicu', en: 'Submit a match', de: 'Spiel vorschlagen', it: 'Proponi partita' },
  // App Mode (match states)
  'appMode.preMatch': { hr: 'UTAKMICA USKORO', en: 'MATCH SOON', de: 'SPIEL BALD', it: 'PARTITA A BREVE' },
  'appMode.liveMatch': { hr: 'UTAKMICA U TIJEKU', en: 'MATCH IN PROGRESS', de: 'SPIEL LÄUFT', it: 'PARTITA IN CORSO' },
  'appMode.postMatch': { hr: 'ZAVRŠENO', en: 'FINISHED', de: 'BEENDET', it: 'FINITO' },
  'appMode.expectCrowds': { hr: 'Očekuj gužvu oko stadiona i u kafićima', en: 'Expect crowds near stadium and in cafes', de: 'Erwarte Gedränge am Stadion und in Cafés', it: 'Aspettati folla vicino allo stadio e nei bar' },
  'appMode.cityWatching': { hr: 'Grad prati utakmicu', en: 'City is watching the match', de: 'Die Stadt verfolgt das Spiel', it: 'La città segue la partita' },
  'appMode.talkingAbout': { hr: 'Večeras se priča o ovome', en: 'Everyone is talking about this tonight', de: 'Darüber spricht man heute Abend', it: 'Stasera tutti ne parlano' },
  'appMode.ctxParking': { hr: 'Očekuj popunjenost', en: 'Expect full parking', de: 'Parkplätze voll', it: 'Parcheggi pieni' },
  'appMode.ctxCafes': { hr: 'Veća posjećenost', en: 'Higher cafe traffic', de: 'Mehr Cafébesucher', it: 'Più traffico nei bar' },
  'appMode.ctxTraffic': { hr: 'Pojačan promet', en: 'Increased traffic', de: 'Erhöhter Verkehr', it: 'Traffico intenso' },
  // Sports freshness
  'sports.noFreshData': { hr: 'Nema svježih sportskih podataka', en: 'No fresh sports data available', de: 'Keine aktuellen Sportdaten verfügbar', it: 'Nessun dato sportivo aggiornato' },
  'sports.sourceUpdated': { hr: 'Izvor: {source} · Ažurirano: {time}', en: 'Source: {source} · Updated: {time}', de: 'Quelle: {source} · Aktualisiert: {time}', it: 'Fonte: {source} · Aggiornato: {time}' },
  'sports.openExternal': { hr: 'Otvori SofaScore / Flashscore', en: 'Open SofaScore / Flashscore', de: 'SofaScore / Flashscore öffnen', it: 'Apri SofaScore / Flashscore' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function detectLanguage(): Language {
  const browserLang = navigator.language.toLowerCase().slice(0, 2);
  if (browserLang === 'hr') return 'hr';
  if (browserLang === 'de') return 'de';
  if (browserLang === 'it') return 'it';
  if (browserLang === 'en') return 'en';
  return 'hr';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('zadariq-lang');
    return (saved as Language) || detectLanguage();
  });

  useEffect(() => {
    localStorage.setItem('zadariq-lang', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
