// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/sunday-open-shops.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function zagrebNow() {
  return new Date(
    (/* @__PURE__ */ new Date()).toLocaleString("en-US", { timeZone: "Europe/Zagreb" })
  );
}
function isoDate(d) {
  return d.toISOString().slice(0, 10);
}
function upcomingSunday() {
  const d = zagrebNow();
  d.setDate(d.getDate() + (7 - d.getDay()) % 7);
  return isoDate(d);
}

// src/lib/mcp/tools/sunday-open-shops.ts
var sunday_open_shops_default = defineTool({
  name: "sunday_open_shops",
  title: "Shops open on Sunday",
  description: "List shops in Zadar that work on a given working Sunday, with address and opening hours. Defaults to the upcoming Sunday.",
  inputSchema: {
    sunday_date: z.string().optional().describe("Sunday date in YYYY-MM-DD format. Defaults to the upcoming Sunday.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sunday_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const date = sunday_date ?? upcomingSunday();
    const { data: schedule, error } = await supabase.from("shop_sunday_schedule").select("business_id, open_time, close_time, notes").eq("sunday_date", date);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!schedule?.length) {
      return { content: [{ type: "text", text: `No shops recorded for ${date}.` }] };
    }
    const placeIds = schedule.map((s) => s.business_id).filter((id) => id.startsWith("ap_")).map((id) => id.slice(3));
    const places = placeIds.length ? (await supabase.from("pending_places").select("id, proposed_name, proposed_address, lat, lng").in("id", placeIds)).data ?? [] : [];
    const byId = new Map(places.map((p) => [p.id, p]));
    const shops = schedule.map((s) => {
      const p = s.business_id.startsWith("ap_") ? byId.get(s.business_id.slice(3)) : void 0;
      return {
        id: s.business_id,
        name: p?.proposed_name ?? s.business_id,
        address: p?.proposed_address ?? null,
        lat: p?.lat ?? null,
        lng: p?.lng ?? null,
        open_time: s.open_time,
        close_time: s.close_time,
        notes: s.notes
      };
    });
    const text = [
      `Working Sunday ${date} \u2014 ${shops.length} shops:`,
      ...shops.map(
        (s) => `- ${s.name}${s.address ? `, ${s.address}` : ""} \u2014 ${s.open_time ?? "?"}\u2013${s.close_time ?? "?"}`
      )
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: { sunday_date: date, shops } };
  }
});

// src/lib/mcp/tools/city-alerts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var city_alerts_default = defineTool2({
  name: "city_alerts",
  title: "Active city alerts",
  description: "List currently active alerts for Zadar (traffic, outages, weather, earthquakes), sorted by priority.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Maximum number of alerts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const max = Math.min(Math.max(limit ?? 10, 1), 50);
    const { data, error } = await supabaseForUser(ctx).from("city_alerts").select("title, summary, type, priority, source, source_url, valid_until").gt("valid_until", (/* @__PURE__ */ new Date()).toISOString()).order("priority", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "No active alerts right now." }] };
    const text = data.map((a) => `- [${a.type}] ${a.title} \u2014 ${a.summary} (izvor: ${a.source})`).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { alerts: data } };
  }
});

// src/lib/mcp/tools/city-events.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var city_events_default = defineTool3({
  name: "city_events",
  title: "Upcoming city events",
  description: "List upcoming events in Zadar and the surrounding region.",
  inputSchema: {
    days_ahead: z3.number().int().optional().describe("How many days ahead to look (default 14)."),
    category: z3.string().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days_ahead, category }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const days = Math.min(Math.max(days_ahead ?? 14, 1), 120);
    const from = zagrebNow();
    const to = new Date(from);
    to.setDate(to.getDate() + days);
    let query = supabaseForUser(ctx).from("city_events").select("title, description, venue, location, category, event_date_from, event_date_to, website_url").gte("event_date_from", isoDate(from)).lte("event_date_from", isoDate(to)).order("event_date_from", { ascending: true }).limit(50);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "No upcoming events found." }] };
    const text = data.map((e) => `- ${e.event_date_from ?? "?"} \xB7 ${e.title}${e.venue ? ` @ ${e.venue}` : ""}`).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { events: data } };
  }
});

// src/lib/mcp/tools/search-places.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var search_places_default = defineTool4({
  name: "search_places",
  title: "Search places",
  description: "Search approved places in Zadar (shops, cafes, services) by name or address. Returns address and coordinates.",
  inputSchema: {
    query: z4.string().describe("Name or address fragment to search for."),
    category: z4.string().optional().describe("Optional category filter, e.g. shop, cafes, pharmacy.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const term = query.trim();
    if (!term) return { content: [{ type: "text", text: "Empty query." }], isError: true };
    let q = supabaseForUser(ctx).from("pending_places").select("id, proposed_name, proposed_address, category, lat, lng, phone, website").eq("status", "approved").or(`proposed_name.ilike.%${term}%,proposed_address.ilike.%${term}%`).limit(25);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: `No places found for "${term}".` }] };
    const places = data.map((p) => ({
      id: `ap_${p.id}`,
      name: p.proposed_name,
      address: p.proposed_address,
      category: p.category,
      lat: p.lat,
      lng: p.lng,
      phone: p.phone,
      website: p.website
    }));
    const text = places.map((p) => `- ${p.name} \u2014 ${p.address} (${p.category})`).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { places } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yxfaovaigwdbziewnppx";
var mcp_default = defineMcp({
  name: "zadariq-mcp",
  title: "ZadarIQ",
  version: "0.1.0",
  instructions: "Live city data for Zadar, Croatia. Use `sunday_open_shops` for shops working on a given working Sunday, `city_alerts` for active traffic/outage/weather alerts, `city_events` for upcoming events, and `search_places` to look up a place's address and coordinates. All times are Europe/Zagreb.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [sunday_open_shops_default, city_alerts_default, city_events_default, search_places_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
